// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/ZsAppMain/AppMain.vue')['default']
    Components: typeof import('./src/components/ZsIcon/components/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSubMeun: typeof import('element-plus/es')['ElSubMeun']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCustomBug: typeof import('~icons/custom/bug')['default']
    MenuBar: typeof import('./src/components/ZsMenuBar/MenuBar.vue')['default']
    NavBar: typeof import('./src/components/ZsNavBar/NavBar.vue')['default']
    NavTabs: typeof import('./src/components/NavTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/ZsMenu/components/SubMenu.vue')['default']
    Zs: typeof import('./src/components/zs.vue')['default']
    ZsAppMain: typeof import('./src/components/ZsAppMain/index.vue')['default']
    ZsIcon: typeof import('./src/components/ZsIcon/index.vue')['default']
    ZsLogo: typeof import('./src/components/ZsLogo/index.vue')['default']
    ZsMenu: typeof import('./src/components/ZsMenu/index.vue')['default']
    ZsMenuBar: typeof import('./src/components/ZsMenuBar/index.vue')['default']
    ZsNavBar: typeof import('./src/components/ZsNavBar/index.vue')['default']
    ZsSubMenu: typeof import('./src/components/ZsSubMenu/index.vue')['default']
  }
}
