// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElSubMeun: typeof import('element-plus/es')['ElSubMeun'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    ZsAppMain: typeof import('../src/components/ZsAppMain/index.vue')['default'];
    ZsNavBar: typeof import('../src/components/ZsNavBar/index.vue')['default'];
    ZsMenu: typeof import('../src/components/ZsMenu/index.vue')['default'];
    SubMenu: typeof import('../src/components/ZsMenu/ccomponents/SubMenu.vue')['default'];
  }
}
